version: '3'
services:
  python3:
    build: .
    container_name: 'be-intro'
    working_dir: '/tmp/work/'
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - ./:/tmp/work
    tty: true