services:
  be-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: 'be-intro'
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - ./:/tmp/work
    ports:
      - "${BACKEND_PORT}:8000" 
    tty: true

  fe-app:
    build:
      context: ../fe_jarujaru_intro
      dockerfile: Dockerfile
    container_name: 'fe-intro'
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - ../fe_jarujaru_intro/:/tmp/work
      - fe-node-modules:/tmp/work/node_modules # node_modulesをボリューム管理
      - fe-next-folder:/tmp/work/.next
    ports:
      - "${FRONTEND_PORT}:3000" 
    tty: true

volumes:
  fe-node-modules:
  fe-next-folder: